apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kapil-ji-app
  namespace: argocd
spec:
  destination: 
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source: 
    repoURL: https://github.com/KdSharna/manifest-demo-file.git
    targetRevision: main
    path: .
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
